# Default values for student-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: sriram1113/student-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.7

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type : NodePort
  port: 8080
  protocol: TCP

env:
  name: dev

mysql:
  auth:
    rootPassword: dummy
    database: mydb
  primary:
    service:
      type: NodePort
      nodePort: 32762
  fullnameOverride: docker-mysql
  initdbScriptsConfigMap: mydb-initdb-config
