apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: student-api
  name: {{ include "student-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: student-api-selector
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: student-api-selector
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
            - containerPort: 8080