kind: ConfigMap
apiVersion: v1
metadata:
  name: mydb-initdb-config
data:
  env: dev
  initdb.sql:
    use mydb;
    create table students(
    id int AUTO_INCREMENT PRIMARY KEY,
    firstname varchar(20),
    lastname varchar(100)
    );