apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-api.name" . }}
  labels:
    run: student-api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    app: student-api-selector